### ISSUE TITLE
AttributeError: 'KMeansConstrained' object has no attribute '_check_fit_data' getting while fitting the data

### ISSUE THREAD

**Issue by adinarayanaPalvadi** [joshlk/k-mean-constrained#1]
AttributeError                            Traceback (most recent call last)
<ipython-input-29-de80de7c216a> in <module>
      6     if a>0:
      7         km_constrained = KMeansConstrained(n_clusters=a,size_max=4,size_min=3,init='k-means++',n_init=100,random_state=None)
----> 8         km_constrained.fit(X)
      9         #k_cons.append(km_constrained)

~\AppData\Local\Continuum\anaconda3.1\lib\site-packages\k_means_constrained-0.2.0-py3.7-win-amd64.egg\k_means_constrained\k_means_constrained_.py in fit(self, X, y)
    621         """
    622         random_state = check_random_state(self.random_state)
--> 623         X = self._check_fit_data(X)
    624 
    625         self.cluster_centers_, self.labels_, self.inertia_, self.n_iter_ = \

AttributeError: 'KMeansConstrained' object has no attribute '_check_fit_data'

**Comment by joshlk** [comment]
Thank you for the error report. Unfortunately the first opportunity I have to look into this will be in two weeks time.

In the meantime can you please provide me the version of python, Skl warm and ortools you are using. And provide a minimal working example with dummy data.

Thanks

**Comment by adinarayanaPalvadi** [comment]
scikit-learn version is 0.21.2 and
or tools version is  7.5.7466
The dummy code is as follows
`X = df_size_7[['Latitude','Longitude']].head(5).values
array([[14.6625047, 77.5828207],
       [14.6975793, 77.5834339],
       [14.6865696, 77.5916512],
       [14.6772115, 77.5933416],
       [14.6780301, 77.5935025]])`

KMeansConstrained(n_clusters=5,size_min=2,size_max=1).fit(X)

AttributeError                            Traceback (most recent call last)
<ipython-input-10-94f3fe20f933> in <module>
----> 1 KMeansConstrained(n_clusters=5,size_min=2,size_max=1).fit(X)

~\AppData\Local\Continuum\anaconda3.1\lib\site-packages\k_means_constrained-0.2.0-py3.7-win-amd64.egg\k_means_constrained\k_means_constrained_.py in fit(self, X, y)
    621         """
    622         random_state = check_random_state(self.random_state)
--> 623         X = self._check_fit_data(X)
    624 
    625         self.cluster_centers_, self.labels_, self.inertia_, self.n_iter_ = \

AttributeError: 'KMeansConstrained' object has no attribute '_check_fit_data'

**Comment by joshlk** [comment]
@adinarayanaPalvadi The problem should now be fixed with the latest version (v0.3.1). The easiest way to install is using PyPI:
`pip install k-means-constrained`

**Comment by joshlk** [comment]
Let me know if you have any problems

**Comment by joshlk** [comment]
Closing as no reply. Please comment again if you require further help.
